---
apiVersion: v1
kind: Pod
metadata:
  name: hello-wold
  labels:
    app: netology
spec:
  containers:
  - image: nginx
    name:  hello-wold

---
apiVersion: v1
kind: Pod
metadata:
  name: netology
  labels:
    app: netology-web
spec:
  containers:
  - image: nginx
    name:  netology-web

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc2
spec:
  selector:
    app: netology-web
  ports:
  - protocol: TCP
    port: 80
