apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx01
  namespace: kuber-1-3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx01
          image: nginx:1.25.2
          ports:
          - protocol: TCP
            containerPort: 80
      initContainers:
      - name: wait-up-service
        image: busybox
        command: ['sh', '-c', "sleep 15; until nslookup task2-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for task2-svc; sleep 10; done"]

---
apiVersion: v1
kind: Service
metadata:
  name: task2-svc
  namespace: kuber-1-3
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
