apiVersion: v1
kind: Namespace
metadata:
  name: kuber-2-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/pv
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task1
  namespace: kuber-2-2
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-work
  namespace: kuber-2-2
  labels:
    app: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts:
        - mountPath: /input
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: task1
