
apiVersion: v1
kind: Namespace
metadata:
  name: kuber-2-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: kuber-2-2
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  namespace: kuber-2-2
  name: pod-with-pvc
spec:
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: nfs-pvc
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    env:
    - name: HTTP_PORT
      value: "8080"
    volumeMounts:
    - name: pvc
      mountPath: /tmp/nfs
