---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend
  namespace: kuber-1-5
  labels: 
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kuber-1-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: miltitool
        image: wbitt/network-multitool:latest
        env:
          - name: HTTP_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: kuber-1-5
spec:
  selector:
    app: frontend
  ports:
    - name: nginx
      protocol: TCP
      port: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: kuber-1-5
spec:
  selector:
    app: backend
  ports:
    - name: multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP



