apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-4
  namespace: kuber-1-4
  labels:
    app: kuber-4
spec:
  selector:
    matchLabels:
      app: kuber-4
  replicas: 3
  template:
    metadata:
      labels:
        app: kuber-4
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.2
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: task1-svc
  namespace: kuber-1-4
spec:
  selector:
    app: kuber-4
  ports:
  - name: web
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: multitool
    protocol: TCP
    port: 9002
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  namespace: kuber-1-4
  labels:
    app: kuber-4
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    ports:
    - protocol: TCP
      containerPort: 8081


