---
apiVersion: v1 
kind: Namespace
metadata:
  name: kuber-2-1

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi-tool
  namespace: kuber-2-1
  labels:
    app: homework
spec:
  selector:
    matchLabels:
      name: homework
  template:
    metadata:
      labels:
        name: homework
    spec:

      containers:
      - name: multi-tool
        image: wbitt/network-multitool:latest
        env:
          - name: HTTP_PORT
            value: "8080"
        volumeMounts:
          - name: logs
            mountPath: /node/logs
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        
  