apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: kuber-2-3
data:
  index: "Netology \nHome work \nKubernetes \"Configure applications\"\n#magic___^_^___line\n"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kuber-2-3
  labels:
    app: homework-2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: configmap-nginx
      mountPath: /usr/share/nginx/html/

  volumes:
  - name: configmap-nginx
    configMap:
      name: nginx-config
      items:
      - key: "index"
        path: "index.html"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-svc
  namespace: kuber-2-3
spec:
  selector:
    app: homework-2
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: kuber-2-3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: george-lisikh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-1-svc
            port:
              number: 80
  tls:
  - hosts:
    - george-lisikh.com
    secretName: secret-tls

